
name: Publish to NPM
on:
  push:
    branches:
      - main

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PLATFORM_SA_NPM_TOKEN }}

